'use strict';

// Deterministic explanations of a counterexample.
//
// Everything here is read off simulator state: the cause each service carries
// in `state.derived.health[id].cause` (set by the mesh engine's propagation),
// the pods and their phases, zone and node flags. No text is generated by a
// model; the sentences are templates filled from that state.

const { INCIDENT_CLASS, MESH_ACTION, MESH_FAULT, POD_PHASE } = require('../cloudproof-mesh/constants');
const { nodeReady, volumeAvailable } = require('../cloudproof-mesh/engine');
const { primaryOf, replicaOf } = require('../cloudproof-mesh/world');
const { causalChain, rootCauseOf, worstFailingRoute } = require('./causes');
const { EDGE_SEMANTICS, edgeId, graphModel, layoutWorld } = require('./graph-model');
const { createMonitor, describeInvariant } = require('./invariants');
const { replayTrace } = require('./verify');

const seconds = (ms) => `T+${(ms / 1000).toFixed(1)} s`;

function zoneOf(world, nodeId) {
    return world.nodes.find((node) => node.id === nodeId)?.zone || null;
}

function disruptionPhrase(entry) {
    const action = entry.action;
    if (entry.origin === 'change' || entry.origin === 'operation') {
        if (action.type === MESH_FAULT.POD_CRASH) return 'being replaced by the rollout';
        if (action.type === MESH_ACTION.DRAIN_NODE) return `evicted by the drain of ${action.nodeId}`;
        if (action.type === MESH_ACTION.SCALE) return 'removed by the scale-down';
    }
    if (action.type === MESH_FAULT.NODE_CRASH) return `lost when ${action.nodeId} crashed`;
    if (action.type === MESH_FAULT.ZONE_DEGRADED) return `unavailable because ${action.zoneId} degraded`;
    if (action.type === MESH_FAULT.POD_CRASH) return 'crashed';
    return null;
}

function phaseSuffix(state, pod) {
    if (pod.phase === POD_PHASE.FAILED) return pod.node ? `, restarting on ${pod.node}` : ', waiting to be rescheduled';
    if (pod.phase === POD_PHASE.PENDING) return ', pending with no schedulable node';
    if (pod.phase === POD_PHASE.STARTING) return `, starting on ${pod.node} (ready at ${seconds(pod.readyAtMs)})`;
    return '';
}

// Why one pod is not serving right now, in words. `disruption` is the trace
// entry that took it out of service, when the replay saw one.
function podReason(state, pod, disruption) {
    const world = state.world;
    const phrase = disruption ? disruptionPhrase(disruption) : null;
    if (phrase) return `${phrase}${phaseSuffix(state, pod)}`;
    if (pod.phase === POD_PHASE.FAILED) return pod.node ? `restarting on ${pod.node}` : 'evicted, waiting to be rescheduled';
    if (pod.phase === POD_PHASE.PENDING) return 'pending: no schedulable node';
    if (pod.phase === POD_PHASE.STARTING) return `starting on ${pod.node}, ready at ${seconds(pod.readyAtMs)}`;
    if (!pod.node) return 'not placed';
    if (state.nodes[pod.node].crashed) return `on ${pod.node}, which crashed`;
    const zone = zoneOf(world, pod.node);
    if (state.zones[zone].degraded) return `on ${pod.node} in ${zone}, which is degraded`;
    if (!nodeReady(state, pod.node)) return `on ${pod.node}, which is not ready`;
    const service = world.services.find((item) => item.id === pod.service);
    if (service.volume && !volumeAvailable(state, service.volume)) return 'its volume is unavailable';
    return 'not serving';
}

function servingNow(state, pod) {
    if (pod.phase !== POD_PHASE.RUNNING || !pod.node || !nodeReady(state, pod.node)) return false;
    const service = state.world.services.find((item) => item.id === pod.service);
    return !service.volume || volumeAvailable(state, service.volume);
}

/** For every pod, the trace entry after which it stopped serving (last one wins). */
function podDisruptions(world, trace, invariants) {
    const causes = new Map();
    replayTrace(world, trace, invariants, {
        stopOnViolation: false,
        onStep: ({ entry, before, after }) => {
            if (entry.origin === 'time') return;
            const was = new Map(before.pods.map((pod) => [pod.id, servingNow(before, pod)]));
            for (const pod of after.pods) {
                if (was.get(pod.id) && !servingNow(after, pod)) causes.set(pod.id, entry);
                if (!was.has(pod.id) && entry.origin === 'change') causes.set(pod.id, entry);
            }
        },
    });
    return causes;
}

function listOf(items) {
    if (items.length <= 1) return items.join('');
    return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

function rootDetail(state, root, incidentClass, disruptions, labels) {
    const world = state.world;
    const name = (id) => labels[id] || id;
    const service = world.services.find((item) => item.id === root);
    if (!service) return { sentence: '', pods: [] };
    const health = state.derived.health[root];
    const pods = state.pods.filter((pod) => pod.service === root);
    const down = pods.filter((pod) => !(pod.phase === POD_PHASE.RUNNING && pod.node && nodeReady(state, pod.node)
        && (!service.volume || volumeAvailable(state, service.volume))));
    const reasons = new Map();
    for (const pod of down) {
        const reason = podReason(state, pod, disruptions.get(pod.id));
        (reasons.get(reason) || reasons.set(reason, []).get(reason)).push(pod.id);
    }
    const podText = [...reasons].map(([reason, ids]) => `${listOf(ids)} ${ids.length > 1 ? 'were' : 'was'} ${reason}`);
    const surge = state.rps > world.traffic.rps ? ` Traffic was ${state.rps} rps (×${(state.rps / world.traffic.rps).toFixed(2).replace(/\.?0+$/, '')} of normal).` : '';
    let sentence;
    switch (incidentClass) {
        case INCIDENT_CLASS.INSTANCE_LOSS:
            sentence = `${name(root)} needs ${service.minHealthy} healthy pod${service.minHealthy > 1 ? 's' : ''} and had ${health.healthy}.${podText.length ? ` ${podText.join('; ')}.` : ''}`;
            break;
        case INCIDENT_CLASS.OVERLOAD:
            sentence = `${name(root)} received ${Math.round(health.load)} rps against ${health.capacityRps} rps of capacity (${health.healthy} serving pod${health.healthy === 1 ? '' : 's'} × ${service.podCapacityRps} rps).${surge}${podText.length ? ` ${podText.join('; ')}.` : ''}`;
            break;
        case INCIDENT_CLASS.CACHE_STAMPEDE: {
            const caches = world.services.filter((item) => item.kind === 'cache'
                && world.dependencies.some((edge) => edge.type === 'BACKED_BY' && edge.from === item.id && edge.to === root));
            const which = caches.map((cache) => {
                const cacheHealth = state.derived.health[cache.id];
                if (!cacheHealth.intrinsicUp) return `${name(cache.id)} was down (${cacheHealth.healthy} of ${cache.minHealthy} required pods)`;
                return `${name(cache.id)} was cold`;
            });
            sentence = `${listOf(which)}, so every read fell through to ${name(root)}: ${Math.round(health.load)} rps against ${health.capacityRps} rps of capacity.${surge}`;
            break;
        }
        case INCIDENT_CLASS.STORAGE_UNAVAILABLE: {
            const volume = world.volumes.find((item) => item.id === service.volume);
            sentence = `${name(root)} stores its data on ${volume.id} in ${volume.zone}, which is degraded, so its pods cannot serve.`;
            break;
        }
        case INCIDENT_CLASS.QUEUE_BACKPRESSURE:
        case 'QUEUE_BACKLOG': {
            const runtime = state.services[root];
            const consumers = world.dependencies.filter((edge) => edge.type === 'CONSUMES' && edge.to === root).map((edge) => edge.from);
            const parts = consumers.map((id) => {
                const worker = state.services[id];
                const workerHealth = state.derived.health[id];
                if (worker.stalledUntilMs > state.clockMs) return `${name(id)} is stalled until ${seconds(worker.stalledUntilMs)}`;
                return `${name(id)} drains ${workerHealth.capacityRps} msg/s (${workerHealth.healthy} pods)`;
            });
            const inflow = Math.round(state.derived.inflow[root] || 0);
            sentence = `${name(root)} holds ${Math.round(runtime.backlog)} of ${service.queueCapacity} messages; ${inflow} msg/s arrive while ${listOf(parts) || 'no consumer drains it'}.${surge}`;
            break;
        }
        default:
            sentence = `${name(root)} is unavailable.`;
    }
    return { sentence, pods: down.map((pod) => pod.id) };
}

// The dependency edge a cause travelled along. Writes may have been redirected
// to a promoted replica and cache reads may have fallen through to the
// backing store, so the edge can end one hop before `to`.
function edgeBetween(world, from, to) {
    const direct = world.dependencies.find((edge) => edge.from === from && edge.to === to);
    if (direct) return direct;
    return world.dependencies.find((edge) => edge.from === from && (
        replicaOf(world, edge.to) === to
        || primaryOf(world, edge.to) === to
        || world.dependencies.some((backing) => backing.type === 'BACKED_BY' && backing.from === edge.to && backing.to === to)
    )) || null;
}

/**
 * The narrative and the root-cause path for a violation at `state`.
 * `trace` is the materialized trace that led here; `withoutChange` is the
 * state the same faults reach without the change, when available.
 */
function explainViolation(state, violation, invariants, { trace = [], labels = {}, withoutChange = null } = {}) {
    const world = state.world;
    const name = (id) => labels[id] || id;
    const invariant = invariants.find((item) => item.id === violation.invariant);
    const cause = rootCauseOf(state, violation, invariant);
    const disruptions = trace.length ? podDisruptions(world, trace, invariants) : new Map();
    const detail = cause.root ? rootDetail(state, cause.root, cause.incidentClass, disruptions, labels) : { sentence: '', pods: [] };
    const sentences = [];
    if (detail.sentence) sentences.push(detail.sentence);
    const chainEdges = [];
    for (let index = cause.chain.length - 1; index > 0; index -= 1) {
        const upstream = cause.chain[index - 1];
        const downstream = cause.chain[index];
        const edge = edgeBetween(world, upstream, downstream);
        if (edge) chainEdges.push(edgeId(edge));
        const verb = edge ? EDGE_SEMANTICS[edge.type].verb : 'depends on';
        let link = `${name(upstream)} ${verb} ${name(downstream)}`;
        if (edge && edge.to !== downstream) {
            const backing = world.dependencies.find((item) => item.type === 'BACKED_BY' && item.from === edge.to && item.to === downstream);
            if (backing) {
                chainEdges.push(edgeId(backing));
                link = `${name(upstream)} ${verb} ${name(edge.to)}, whose reads now land on ${name(downstream)}`;
            } else {
                link = `${name(upstream)} ${verb} ${name(edge.to)}, now served by ${name(downstream)}`;
            }
        }
        const full = edge?.type === 'PUBLISHES' && cause.incidentClass === INCIDENT_CLASS.QUEUE_BACKPRESSURE ? ', which is full' : '';
        sentences.push(`${link}${full}, so ${name(upstream)} failed too.`);
    }
    if (cause.route) {
        const route = world.routes.find((item) => item.id === cause.route);
        sentences.push(`The ${route.id} route (${route.sharePct}% of traffic) enters ${name(route.entry)} and failed: "${describeInvariant(invariant, labels)}" expected ${violation.expected}, observed ${violation.observed}.`);
    } else {
        sentences.push(`Invariant "${describeInvariant(invariant, labels)}" expected ${violation.expected}, observed ${violation.observed}.`);
    }
    if (withoutChange && cause.root && withoutChange.derived.health[cause.root]) {
        const other = withoutChange.derived.health[cause.root];
        const same = createMonitor(invariant).observe(withoutChange);
        const load = Math.round(other.load);
        const rootService = world.services.find((item) => item.id === cause.root);
        const facts = rootService.kind === 'queue'
            ? `${name(cause.root)} held ${Math.round(withoutChange.services[cause.root].backlog)} messages`
            : `${name(cause.root)} had ${other.healthy} healthy pod${other.healthy === 1 ? '' : 's'}${load ? ` and ${load} rps of load` : ''}`;
        sentences.push(`With the same faults and no change, ${facts} at this moment, and ${same ? 'the invariant failed anyway' : 'the invariant held'}.`);
    }

    // Root-cause path. The trace is minimal, so every action in it is needed:
    // each one is a trigger. Then whatever carried the failure to the root,
    // the root, the dependency chain upward, the route and the invariant.
    const path = [];
    const highlight = { services: new Set(), zones: new Set(), nodes: new Set(), routes: new Set(), edges: new Set(chainEdges), pods: new Set() };
    trace.forEach((entry, index) => {
        if (entry.origin === 'time') return;
        const action = entry.action;
        path.push({ kind: entry.origin, id: `${entry.origin}:${index}`, label: shortTitle(entry, labels) });
        if (action.zoneId) highlight.zones.add(action.zoneId);
        if (action.nodeId) highlight.nodes.add(action.nodeId);
        if (action.serviceId) highlight.services.add(action.serviceId);
        if (action.podId) highlight.pods.add(action.podId);
    });
    if (cause.root) {
        const via = [];
        if (cause.incidentClass === INCIDENT_CLASS.CACHE_STAMPEDE) {
            const caches = world.services.filter((item) => item.kind === 'cache'
                && world.dependencies.some((edge) => edge.type === 'BACKED_BY' && edge.from === item.id && edge.to === cause.root));
            for (const cache of caches) {
                const health = state.derived.health[cache.id];
                const cold = state.services[cache.id].coldUntilMs > state.clockMs;
                if (health.intrinsicUp && !cold) continue;
                via.push({ kind: 'service', id: cache.id, label: health.intrinsicUp ? `${name(cache.id)} cold` : `${name(cache.id)} down (${health.healthy}/${cache.minHealthy} healthy)` });
                highlight.edges.add(edgeId(world.dependencies.find((edge) => edge.type === 'BACKED_BY' && edge.from === cache.id)));
                for (const pod of state.pods.filter((item) => item.service === cache.id && !servingNow(state, item))) highlight.pods.add(pod.id);
            }
        }
        if (['QUEUE_BACKLOG', INCIDENT_CLASS.QUEUE_BACKPRESSURE].includes(cause.incidentClass)) {
            for (const edge of world.dependencies.filter((item) => item.type === 'CONSUMES' && item.to === cause.root)) {
                const health = state.derived.health[edge.from];
                const stalled = state.services[edge.from].stalledUntilMs > state.clockMs;
                via.push({ kind: 'service', id: edge.from, label: stalled ? `${name(edge.from)} stalled` : `${name(edge.from)} drains ${health.capacityRps}/s` });
                highlight.edges.add(edgeId(edge));
            }
        }
        for (const item of via) { path.push(item); highlight.services.add(item.id); }
        if (detail.pods.length && [INCIDENT_CLASS.INSTANCE_LOSS, INCIDENT_CLASS.OVERLOAD].includes(cause.incidentClass)) {
            path.push({ kind: 'pods', id: detail.pods.join(','), ids: detail.pods, label: `${listOf(detail.pods)} not serving` });
            detail.pods.forEach((id) => highlight.pods.add(id));
        }
        const health = state.derived.health[cause.root];
        const service = world.services.find((item) => item.id === cause.root);
        let status;
        if (service.kind === 'queue') status = `backlog ${Math.round(state.services[cause.root].backlog)}/${service.queueCapacity}`;
        else if (health.overloaded) status = `overloaded (${Math.round(health.load)}/${health.capacityRps} rps)`;
        else if (!health.intrinsicUp) status = `${health.healthy}/${service.minHealthy} healthy`;
        else status = `${health.healthy} healthy`;
        path.push({ kind: 'service', id: cause.root, label: `${name(cause.root)} ${status}` });
        highlight.services.add(cause.root);
    }
    for (let index = cause.chain.length - 2; index >= 0; index -= 1) {
        path.push({ kind: 'service', id: cause.chain[index], label: `${name(cause.chain[index])} fails` });
        highlight.services.add(cause.chain[index]);
    }
    if (cause.route) {
        path.push({ kind: 'route', id: cause.route, label: `${cause.route} route failing` });
        highlight.routes.add(cause.route);
    }
    path.push({ kind: 'invariant', id: invariant.id, label: describeInvariant(invariant, labels) });
    return {
        invariant: invariant.id,
        invariantText: describeInvariant(invariant, labels),
        expected: violation.expected,
        observed: violation.observed,
        atMs: violation.atMs,
        route: cause.route,
        root: cause.root,
        incidentClass: cause.incidentClass,
        chain: cause.chain,
        chainEdges,
        pods: detail.pods,
        narrative: sentences,
        path,
        highlight: Object.fromEntries(Object.entries(highlight).map(([key, set]) => [key, [...set].sort()])),
    };
}

function shortTitle(entry, labels) {
    const name = (id) => labels[id] || id;
    const action = entry.action;
    if (entry.origin === 'change') {
        if (action.type === MESH_FAULT.POD_CRASH) return `rollout replaces ${action.podId}`;
        if (action.type === MESH_ACTION.SCALE) return `scale ${name(action.serviceId)} to ${action.replicas}`;
        if (action.type === MESH_ACTION.DRAIN_NODE) return `drain ${action.nodeId}`;
    }
    switch (action.type) {
        case MESH_FAULT.TRAFFIC_SPIKE: return `traffic ×${action.factor}`;
        case MESH_FAULT.ZONE_DEGRADED: return `${action.zoneId} degraded`;
        case MESH_FAULT.NODE_CRASH: return `${action.nodeId} crashes`;
        case MESH_FAULT.CACHE_FLUSH: return `${name(action.serviceId)} flushed`;
        case MESH_FAULT.CONSUMER_STALL: return `${name(action.serviceId)} stalls ${(action.durationMs / 1000).toFixed(1)} s`;
        case MESH_FAULT.POD_CRASH: return `${action.podId} crashes`;
        case MESH_ACTION.RECOVER_ZONE: return `${action.zoneId} recovers`;
        case MESH_ACTION.TRAFFIC_SHIFT: return `traffic back to ${action.rps} rps`;
        default: return actionTitle(entry, labels);
    }
}

function actionTitle(entry, labels) {
    const name = (id) => labels[id] || id;
    const action = entry.action;
    if (entry.label) return entry.label;
    switch (action.type) {
        case MESH_ACTION.ADVANCE_TIME: return `${(action.ms / 1000).toFixed(1)} s pass`;
        case MESH_ACTION.SCALE: return `Scale ${name(action.serviceId)} to ${action.replicas}`;
        case MESH_ACTION.TRAFFIC_SHIFT: return `Traffic set to ${action.rps} rps`;
        case MESH_ACTION.DRAIN_NODE: return `Drain ${action.nodeId}`;
        case MESH_ACTION.UNCORDON_NODE: return `Uncordon ${action.nodeId}`;
        case MESH_ACTION.RECOVER_NODE: return `${action.nodeId} recovers`;
        case MESH_ACTION.RECOVER_ZONE: return `${action.zoneId} recovers`;
        case MESH_FAULT.NODE_CRASH: return `${action.nodeId} crashes`;
        case MESH_FAULT.ZONE_DEGRADED: return `${action.zoneId} degraded`;
        case MESH_FAULT.POD_CRASH: return `${action.podId} crashes`;
        case MESH_FAULT.CACHE_FLUSH: return `${name(action.serviceId)} flushed`;
        case MESH_FAULT.CONSUMER_STALL: return `${name(action.serviceId)} stalls for ${(action.durationMs / 1000).toFixed(1)} s`;
        case MESH_FAULT.TRAFFIC_SPIKE: return `Traffic spikes ×${action.factor}`;
        default: return action.type;
    }
}

// What changed between two states, as ids for highlighting and as sentences.
function stateDelta(before, after, labels) {
    const name = (id) => labels[id] || id;
    const world = after.world;
    const services = [];
    const notes = [];
    for (const service of world.services) {
        const was = before.derived.health[service.id];
        const now = after.derived.health[service.id];
        if (was.up !== now.up || was.healthy !== now.healthy || Boolean(was.overloaded) !== Boolean(now.overloaded)) services.push(service.id);
        if (was.up && !now.up) notes.push(`${name(service.id)} went down${now.overloaded ? ' (overloaded)' : now.cause?.kind === 'dependency' ? ` (depends on ${name(now.cause.via)})` : ''}`);
        else if (!was.up && now.up) notes.push(`${name(service.id)} recovered`);
        else if (was.healthy !== now.healthy) notes.push(`${name(service.id)} ${was.healthy} → ${now.healthy} healthy`);
        if (!before.services[service.id].promoted && after.services[service.id].promoted) notes.push(`${name(replicaOf(world, service.id))} promoted to primary`);
    }
    const zones = world.zones.filter((zone) => before.zones[zone.id].degraded !== after.zones[zone.id].degraded).map((zone) => zone.id);
    const nodes = world.nodes.filter((node) => before.nodes[node.id].crashed !== after.nodes[node.id].crashed
        || before.nodes[node.id].cordoned !== after.nodes[node.id].cordoned).map((node) => node.id);
    const routes = world.routes.filter((route) => before.derived.routes[route.id].failing !== after.derived.routes[route.id].failing).map((route) => route.id);
    for (const route of routes) notes.push(`${route} route ${after.derived.routes[route].failing ? 'failing' : 'serving again'}`);
    if (before.rps !== after.rps) notes.unshift(`traffic ${before.rps} → ${after.rps} rps`);
    const changed = new Set(services);
    const edges = world.dependencies.filter((edge) => changed.has(edge.from) && changed.has(edge.to)).map(edgeId);
    return { services, zones, nodes, routes, edges, notes };
}

/**
 * Replay a trace and produce one timeline event per trace entry, each with
 * the graph before and after, the ids it touched, and the violations.
 */
function buildTimeline(world, trace, invariants, { labels = {}, versions = {} } = {}) {
    const layout = layoutWorld(world);
    const meta = { labels, versions, layout };
    const events = [];
    let firstState = null;
    const replay = replayTrace(world, trace, invariants, {
        onStep: ({ index, entry, before, after, violations }) => {
            if (!firstState) firstState = before;
            const delta = stateDelta(before, after, labels);
            const target = entry.action.nodeId || entry.action.zoneId || entry.action.serviceId || entry.action.podId || null;
            events.push({
                index,
                atMs: entry.atMs,
                endMs: after.clockMs,
                origin: entry.origin,
                type: entry.action.type,
                target,
                title: actionTitle(entry, labels),
                notes: delta.notes,
                affected: delta,
                before: graphModel(before, meta),
                after: graphModel(after, meta),
                violations: violations || [],
            });
        },
    });
    return { events, violations: replay.violations, transitions: replay.transitions, initial: firstState ? graphModel(firstState, meta) : null };
}

module.exports = {
    actionTitle,
    buildTimeline,
    causalChain,
    explainViolation,
    podDisruptions,
    rootCauseOf,
    shortTitle,
    stateDelta,
    worstFailingRoute,
};
