'use strict';

// Incident Lab: replay a recorded outage, find its first violation, shrink it
// to its causal core, and find when (and whether) the system recovered.
//
// Committed incidents are identifiers, not recordings: each names a Phase III
// template and seed, and the world and its natural (outcome-blind) schedule
// are regenerated by packages/cloudproof-mesh/generator.js. Evidence bundles
// exported from Verify Change can be imported and replayed the same way.

const { MESH_ACTION, MESH_FAULT } = require('../cloudproof-mesh/constants');
const { generateWorld, naturalSchedule } = require('../cloudproof-mesh/generator');
const { generatedLabels } = require('./architecture');
const { applyReadinessDelay } = require('./faults');
const { createMonitor, observeAll } = require('./invariants');
const { replayTrace } = require('./verify');
const { createMeshState, step, tick } = require('../cloudproof-mesh/engine');
const { TIMING } = require('../cloudproof-mesh/constants');

const SLO = Object.freeze([{ id: 'error-budget', kind: 'error-budget', maxPct: 20 }]);

// Chosen from a scan of natural schedules (seeds 100-159) for traces that run
// well past their first incident and cover four incident classes.
const COMMITTED = Object.freeze([
    { id: 'natural-T2-108', template: 'T2', seed: 108, title: 'Capacity lost while traffic was shifted up', source: 'Phase III natural schedule' },
    { id: 'natural-T2-105', template: 'T2', seed: 105, title: 'A drain after a long, noisy afternoon', source: 'Phase III natural schedule' },
    { id: 'natural-T2-133', template: 'T2', seed: 133, title: 'Cache flush during a scale event', source: 'Phase III natural schedule' },
    { id: 'natural-T5-156', template: 'T5', seed: 156, title: 'Order backlog after a consumer stall', source: 'Phase III natural schedule' },
]);

const FAULT_TYPES = new Set(Object.values(MESH_FAULT));

function originOf(action) {
    if (action.type === MESH_ACTION.ADVANCE_TIME) return 'time';
    return FAULT_TYPES.has(action.type) ? 'fault' : 'operation';
}

function listIncidents() {
    return COMMITTED.map((item) => ({ ...item }));
}

function loadIncident(id) {
    const entry = COMMITTED.find((item) => item.id === id);
    if (!entry) throw new TypeError(`unknown incident: ${id}`);
    const { world } = generateWorld(entry.seed, entry.template);
    const { actions } = naturalSchedule(entry.seed, world);
    let clock = 0;
    const trace = actions.map((action) => {
        const item = { action, origin: originOf(action), label: null, atMs: clock };
        if (action.type === MESH_ACTION.ADVANCE_TIME) clock += action.ms;
        return item;
    });
    return {
        id: entry.id,
        title: entry.title,
        source: `${entry.source} · template ${entry.template} · seed ${entry.seed}`,
        world,
        labels: generatedLabels(world),
        versions: {},
        invariants: SLO.map((item) => ({ ...item })),
        trace,
        requireChange: false,
    };
}

/** An incident from an evidence bundle's original counterexample trace. */
function incidentFromEvidence(bundle) {
    if (!bundle?.counterexample) throw new TypeError('this evidence bundle has no counterexample to replay');
    const world = bundle.counterexample.readinessDelay ? applyReadinessDelay(bundle.topology.world) : bundle.topology.world;
    return {
        id: `evidence-${bundle.digests.bundle.slice(0, 12)}`,
        title: bundle.changeSummary,
        source: `evidence bundle ${bundle.digests.bundle.slice(0, 12)} · ${bundle.scenario.name || bundle.scenario.id || 'imported'}`,
        world,
        labels: bundle.labels || {},
        versions: bundle.versions || {},
        invariants: bundle.invariants.map(({ description, ...rest }) => rest),
        trace: bundle.counterexample.original.trace,
        requireChange: true,
        target: bundle.counterexample.primary.invariant,
        bundle,
    };
}

/**
 * Run the whole recording once, tick by tick: when invariants first fail,
 * and the first instant after that when every invariant holds again.
 */
function incidentOutline(world, trace, invariants) {
    let state = createMeshState(world);
    const monitors = invariants.map(createMonitor);
    let first = null;
    let recoveredAtMs = null;
    let violatingMs = 0;
    const observe = () => {
        const found = observeAll(monitors, state);
        if (found.length) {
            if (!first) first = found;
            recoveredAtMs = null;
        } else if (first && recoveredAtMs === null) {
            recoveredAtMs = state.clockMs;
        }
        return found.length > 0;
    };
    for (const entry of trace) {
        if (entry.action.type === MESH_ACTION.ADVANCE_TIME) {
            for (let elapsed = 0; elapsed < entry.action.ms; elapsed += TIMING.tickMs) {
                tick(state);
                if (observe()) violatingMs += TIMING.tickMs;
            }
        } else {
            state = step(state, entry.action).state;
            observe();
        }
    }
    const endMs = state.clockMs;
    return {
        firstViolation: first ? first[0] : null,
        recoveredAtMs,
        recovered: Boolean(first) && recoveredAtMs !== null,
        violatingMs,
        endMs,
        actions: trace.length,
    };
}

/** Cut the recording at its first violation (the counterexample to shrink). */
function incidentPrefix(world, trace, invariants, target = null) {
    const replay = replayTrace(world, trace, invariants);
    if (!replay.violations) return null;
    const hit = target ? replay.violations.find((item) => item.invariant === target) || replay.violations[0] : replay.violations[0];
    const cut = trace.slice(0, hit.entry + 1).map((entry) => ({ ...entry }));
    const last = cut[cut.length - 1];
    if (last.action.type === MESH_ACTION.ADVANCE_TIME) cut[cut.length - 1] = { ...last, action: { ...last.action, ms: hit.atMs - hit.entryStartMs } };
    return { trace: cut, violation: hit, violations: replay.violations };
}

module.exports = { COMMITTED, SLO, incidentFromEvidence, incidentOutline, incidentPrefix, listIncidents, loadIncident };
