#!/usr/bin/env node
/**
 * build-web.js — bundles the engine for the browser, with no build tooling.
 *
 * Forty lines instead of webpack, and the reason is not minimalism for its own
 * sake: this project's whole claim is that the consensus engine and the vector
 * index are hand-written and understandable. Introducing a build step that
 * nobody can read to ship a demo of code everybody can read would be a strange
 * trade. It also means the deploy has zero npm dependencies and cannot rot.
 *
 * The bundle wraps each CommonJS module in a factory and provides a tiny
 * `require` that resolves relative paths against a registry. Node-only modules
 * (`fs`, `path`, `axios`) resolve to stubs that throw *if called* — nothing on
 * the browser path calls them, because the simulated cluster passes
 * `storagePath: false` and its own transport.
 *
 *   node tools/build-web.js   →   web/bundle.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'web', 'bundle.js');

// Order does not matter — the registry is lazy — but keeping it dependency-first
// makes the output readable, which is the point.
const MODULES = [
    'replica/quantize.js',
    'replica/sparse.js',
    'replica/hnsw.js',
    'replica/agent-state.js',
    'replica/state-machine.js',
    'replica/log-store.js',
    'replica/raft.js',
    'packages/protocol/events.js',
    'packages/simulator/invariants.js',
    'packages/simulator/flight-recorder.js',
    'packages/agent-runtime/index.js',
    'packages/workloads/extended.js',
    'packages/workloads/agent-refund.js',
    'packages/workloads/index.js',
    'packages/workloads/plain-english.js',
    'packages/scenario-dsl/index.js',
    'sim/simulator.js',
    'sim/decision-tape.js',
    'sim/linearizability.js',
    'sim/cluster.js',
    'sim/bug-museum.js',
];

const STUBS = `
// Node built-ins that the browser path never reaches. They throw rather than
// returning undefined so that if the browser path ever *does* reach them, it
// fails loudly at the call site instead of producing a confusing TypeError
// three frames away.
const __stub = (name) => new Proxy({}, {
  get: (_, prop) => () => {
    throw new Error(\`\${name}.\${String(prop)} is not available in the browser build\`);
  },
});
// A pure-JS FNV-1a stand-in for crypto.createHash, used only by
// HnswIndex#checksum. The browser has SubtleCrypto but it is async, and
// checksum() is synchronous by design — every caller compares it inline. A
// 128-bit non-cryptographic digest is the right trade here: this is a
// divergence detector, not a security primitive, and the property that matters
// is that two identical graphs hash the same within one process.
const __syncHash = () => {
  let bytes = '';
  return {
    update(data) { bytes += String(data); return this; },
    digest() {
      let out = '';
      for (let lane = 0; lane < 4; lane += 1) {
        let h = 2166136261 ^ (lane * 0x9e3779b9);
        for (let i = lane; i < bytes.length; i += 1) {
          h ^= bytes.charCodeAt(i);
          h = Math.imul(h, 16777619);
        }
        out += (h >>> 0).toString(16).padStart(8, '0');
      }
      return out;
    },
  };
};

const __builtins = {
  fs: __stub('fs'),
  'fs/promises': __stub('fs/promises'),
  path: {
    join: (...parts) => parts.filter(Boolean).join('/'),
    dirname: (p) => p.split('/').slice(0, -1).join('/') || '.',
  },
  crypto: { createHash: __syncHash },
  axios: __stub('axios'),
};

// Node 18+ allows the node: prefix alongside the bare name. Aliasing both
// spellings costs one line and avoids a resolution failure that only shows up
// at page load, long after the build reported success.
for (const name of Object.keys(__builtins)) __builtins['node:' + name] = __builtins[name];
`;

function bundle() {
    const parts = [];
    parts.push('/* CloudProof browser bundle — generated by tools/build-web.js. Do not edit. */');
    parts.push('(function (global) {');
    parts.push("'use strict';");
    parts.push(STUBS);
    parts.push('const __registry = {};');
    parts.push('const __cache = {};');

    parts.push(`
function __resolve(from, request) {
  if (__builtins[request]) return { builtin: __builtins[request] };
  // A request that names a registry entry outright is taken as-is. Without
  // this, the entry point's 'sim/cluster.js' would be resolved relative to the
  // synthetic entry module and become 'web/sim/cluster.js'.
  if (__registry[request]) return { id: request };
  const base = from.split('/').slice(0, -1);
  const segments = request.split('/');
  for (const segment of segments) {
    if (segment === '.') continue;
    else if (segment === '..') base.pop();
    else base.push(segment);
  }
  let id = base.join('/');
  if (!__registry[id] && __registry[id + '.js']) id += '.js';
  if (!__registry[id]) throw new Error('cannot resolve ' + request + ' from ' + from);
  return { id };
}

function __require(from, request) {
  const resolved = __resolve(from, request);
  if (resolved.builtin) return resolved.builtin;
  if (__cache[resolved.id]) return __cache[resolved.id].exports;
  const module = { exports: {} };
  __cache[resolved.id] = module;
  __registry[resolved.id](module, module.exports, (r) => __require(resolved.id, r));
  return module.exports;
}
`);

    for (const relative of MODULES) {
        const source = fs.readFileSync(path.join(ROOT, relative), 'utf8');
        parts.push(`__registry[${JSON.stringify(relative)}] = function (module, exports, require) {`);
        parts.push(source);
        parts.push('};');
    }

    parts.push(`
// A single entry point on window. Everything the page needs, and nothing else.
global.cloudProof = {
  cluster: __require('web/entry.js', 'sim/cluster.js'),
  simulator: __require('web/entry.js', 'sim/simulator.js'),
  linearizability: __require('web/entry.js', 'sim/linearizability.js'),
  hnsw: __require('web/entry.js', 'replica/hnsw.js'),
  quantize: __require('web/entry.js', 'replica/quantize.js'),
  sparse: __require('web/entry.js', 'replica/sparse.js'),
  stateMachine: __require('web/entry.js', 'replica/state-machine.js'),
  protocol: __require('web/entry.js', 'packages/protocol/events.js'),
  recorder: __require('web/entry.js', 'packages/simulator/flight-recorder.js'),
  workloads: __require('web/entry.js', 'packages/workloads/index.js'),
  plainEnglish: __require('web/entry.js', 'packages/workloads/plain-english.js'),
  invariants: __require('web/entry.js', 'packages/simulator/invariants.js'),
  scenario: __require('web/entry.js', 'packages/scenario-dsl/index.js'),
  bugMuseum: __require('web/entry.js', 'sim/bug-museum.js'),
};
})(typeof window !== 'undefined' ? window : globalThis);
`);

    return parts.join('\n');
}

fs.mkdirSync(path.join(ROOT, 'web'), { recursive: true });
const output = bundle();
fs.writeFileSync(OUT, output);

const ASSETS = [
    ['apps/systems/index.html', 'web/index.html'],
    ['apps/systems/flight-deck.js', 'web/flight-deck.js'],
    ['apps/lab/bug-museum-ui.js', 'web/bug-museum-ui.js'],
    ['apps/systems/flight-deck.css', 'web/flight-deck.css'],
    ['apps/systems/research-artifact.js', 'web/research-artifact.js'],
    ['apps/systems/research-metrics.json', 'web/research-metrics.json'],
    ['apps/systems/reality-run.json', 'web/reality-run.json'],
    ['apps/lab/bug-museum.css', 'web/bug-museum.css'],
    ['apps/classic/index.html', 'web/classic.html'],
];

for (const [source, destination] of ASSETS) {
    fs.copyFileSync(path.join(ROOT, source), path.join(ROOT, destination));
}

// Keep the authored lab files small and readable while shipping the museum as
// part of the same zero-dependency page.
fs.appendFileSync(path.join(ROOT, 'web', 'flight-deck.js'),
    '\n' + fs.readFileSync(path.join(ROOT, 'apps/lab/bug-museum-ui.js'), 'utf8'));
fs.appendFileSync(path.join(ROOT, 'web', 'flight-deck.css'),
    '\n' + fs.readFileSync(path.join(ROOT, 'apps/lab/bug-museum.css'), 'utf8'));

console.log(`wrote ${OUT}`);
console.log(`  ${MODULES.length} modules · ${(output.length / 1024).toFixed(0)}KB uncompressed`);
console.log('  no dependencies, no minifier, no transpiler');
